### ISSUE TITLE
Constant Crashing on Coomer

### ISSUE THREAD

**Issue by BrandenStoberReal** [AmnesiaIsHere/PartyLib#5]
### Discussed in https://github.com/AmnesiaIsHere/PartyLib/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **Airbourn33** March  6, 2024</sup>
The scrapper crashes a lot. I only just now was watching it as it was parsing asking if I was IP banned or something. This happens on multiple pages. I was able to scrape a rather large page recently without issue for the first time in a long time. 

I have downloaded the latest release and installed it with the same issues.</div>

**Comment by BrandenStoberReal** [comment]
@Airbourn33 Please describe the issue further here.

**Comment by BrandenStoberReal** [comment]
Can you provide a screenshot of the exact error message?

**Comment by BrandenStoberReal** [comment]
Also please provide the creator you are trying to scrape.

**Comment by Airbourn33** [comment]
BobaButtGirl
babyycoco
tattedlix
jasminex

I am sure there were others. I just don't recall.
![party](https://github.com/AmnesiaIsHere/PartyLib/assets/162511635/28c1422e-7639-4586-9a9d-d87f55f679b5)

**Comment by BrandenStoberReal** [comment]
Interesting, looks like some strange API change. Ill look into this for you.

**Comment by BrandenStoberReal** [comment]
This will be addressed in the v2.0.0 rewrite

**Comment by BrandenStoberReal** [comment]
@Airbourn33 I've released an extremely alpha build of the rewrite. Please attempt another scrape and let me know if the issue persists. I've added a logging framework, so if it still breaks you can send me a full log now.

**Comment by Airbourn33** [comment]
Forgive my ignorance, but I am not sure where to download the new version. I got to [here](https://github.com/AmnesiaIsHere/PartyLib/releases/tag/v2.0.0-alpha) and downloaded the Debug and the first Source Code, but neither came with an installer. 

What did I do wrong?

**Comment by BrandenStoberReal** [comment]
The Debug archive is a "snapshot" of the program. You need to unzip it and execute PartyScraper2.0.exe inside the folder. I did not release an installer because this is an alpha build and I don't want people overwriting their installations with an incomplete version.

**Comment by Airbourn33** [comment]
![update](https://github.com/AmnesiaIsHere/PartyLib/assets/162511635/ef5ee060-2f14-4965-84f2-0a340d63ffdf)

I do all this, hit BEGIN SCRAPE and it just sits there like this. 

I was scraping from a program on one drive to storage on another at first. However, when I moved it to the same drive it still did this. 

Love the new UI

**Comment by BrandenStoberReal** [comment]
Hey, glad you like it! I fixed this in recent devbuilds to notify the user, but that is the stage where it is gathering metadata from the party sites. Be patient while it scrapes (depends on your internet speed) and the progress bars at the bottom will start activating once metadata scraping is complete. If the app closes itself, this means something errored and you should send me your logs. Im going to push a new alpha build tonight with slightly better UX.

**Comment by Airbourn33** [comment]
> Hey, glad you like it! I fixed this in recent devbuilds to notify the user, but that is the stage where it is gathering metadata from the party sites. Be patient while it scrapes (depends on your internet speed) and the progress bars at the bottom will start activating once metadata scraping is complete. If the app closes itself, this means something errored and you should send me your logs. Im going to push a new alpha build tonight with slightly better UX.
> 
> Edit: Saw the edit! Glad the issue is fixed.

Can't wait. 

How do I get notifications on when updates drop?

**Comment by BrandenStoberReal** [comment]
On GitHub there's a button to "watch" a repository and it'll automatically update you whenever a new release goes live!
